Даны значения величины заработной платы заемщиков банка (zp) и значения их поведенческого кредитного скоринга (ks):
 zp = [35, 45, 190, 200, 40, 70, 54, 150, 120, 110],
ks = [401, 574, 874, 919, 459, 739, 653, 902, 746, 832].
Найдите ковариацию этих двух величин с помощью элементарных действий, а затем с помощью функции cov из numpy
Полученные значения должны быть равны.
Найдите коэффициент корреляции Пирсона с помощью ковариации и среднеквадратичных отклонений двух признаков, а затем с использованием функций из библиотек numpy и pandas.

Ковариация ищется по формуле:
cov(xy) = M(XY) - M(X) * M(Y)
M - матиматическое ожидание

Формула Пирсона : r = cov(xy)/ (sigma(x) * sigma(y))


In [5]:
#  находим в ручную 
M_XY = ((35*401)+(45*574)+(190*874)+(200*919)+(40*459)+(70*739)+(54*653)+(150*902)+(120*746)+(110*832))/10
M_Y = (401 + 574 + 874 + 919 + 459 + 739 + 653 + 902 + 746 + 832)/10
M_X = (35 + 45 + 190 + 200 + 40 + 70 + 54 + 150 + 120 + 110)/10
Cov = M_XY - M_X * M_Y
Cov

9157.839999999997

In [7]:

import numpy as np

zp = np.array([35, 45, 190, 200, 40, 70, 54, 150, 120, 110])
ks = np.array([401, 574, 874, 919, 459, 739, 653, 902, 746, 832])

cov = np.mean(zp*ks) - np.mean(zp) * np.mean(ks)
cov

9157.839999999997

In [9]:
#  находим с помощью функции
np.cov(zp,ks)

array([[ 3882.93333333, 10175.37777778],
       [10175.37777778, 33854.32222222]])

In [10]:
# расчитывае коэфициент Пирсона 
np.corrcoef(zp,ks)


array([[1.        , 0.88749009],
       [0.88749009, 1.        ]])

Далее находим несмещенную и смещенную ковариации. 

не смещенная

In [11]:
np.cov(zp,ks, ddof = 1)

array([[ 3882.93333333, 10175.37777778],
       [10175.37777778, 33854.32222222]])

In [12]:
np.std(zp, ddof = 1)

62.31318747531162

In [13]:
np.std(ks, ddof = 1)

183.99544076477068

In [16]:
C = 10175.37777778
a = 62.31318747531162
b = 183.99544076477068
r = C/(a*b)
r

0.88749009207411

Смещенная 

In [18]:
np.cov(zp,ks, ddof = 0)

array([[ 3494.64,  9157.84],
       [ 9157.84, 30468.89]])

In [19]:
np.std(zp, ddof = 0)

59.115480206118605

In [20]:
np.std(ks, ddof = 0)

174.55340157098058

In [21]:
C_1 = 9157.84
a_1 = 59.115480206118605
b_1 = 174.55340157098058
r_1 = C/(a*b)
r_1

0.88749009207411

Значени коэффициента кореляции совпадают между собой и равны тому значению которое мы получили через функцию corrcoef